#!/bin/bash
user="$1"
servername="$2"
labPassDir="$HOME/.labauth"
password=`cat $labPassDir/$user`

serverIp=$(grep "$servername" $labPassDir/servers | cut -d " " -f1)
ssh-keygen -R "$serverIp"
ssh-keyscan -H "$serverIp" >> ~/.ssh/known_hosts


sshpass -p"$password" ssh $user@$serverIp 
