#!/bin/bash
user="$1"
servername="$2"
labPassDir="$HOME/.labauth"
password=`cat $labPassDir/$servername-$user`

serverIp=$(grep "$servername" $labPassDir/servers | cut -d " " -f1)
ssh-keygen -R "$serverIp" > /dev/null 2> /dev/null
ssh-keyscan -H "$serverIp" >> ~/.ssh/known_hosts 2> /dev/null

sshpass -p"$password" ssh $user@$serverIp 
